### ISSUE TITLE
Front end add new Payment Method results in PHP error

### ISSUE THREAD

**Issue by ethanpil** [cardknox/woocommerce-gateway-cardknox#25]
Trying to save a card to account from front end *My Account* >> *Payment Methods* page results in fatal PHP error. PHP v8.1. Other cardknox gateway transactions seem to work fine.

```
2023/03/26 16:14:29 [error] 1948#1948: *174562 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: strip_tags(): Argument #1 ($string) must be of type string, array given in wp-content/plugins/woo-cardknox-gateway/includes/class-wc-gateway-cardknox.php:676
Stack trace:
#0 wp-content/plugins/woo-cardknox-gateway/includes/class-wc-gateway-cardknox.php(676): strip_tags()
#1 wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(527): WC_Gateway_Cardknox->add_payment_method()
#2 wp-includes/class-wp-hook.php(308): WC_Form_Handler::add_payment_method_action()
#3 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 wp-includes/plugin.php(565): WP_Hook->do_action()
#5 wp-includes/class-wp.php(797): do_action_ref_array()
#6 wp-includes/functions.php(1332): WP->main()
#7 wp-blog-header.php(16)" while reading response header from upstream, client: 76.91.23.115, server: xxxxxxx.com, request: "POST /my-account/add-payment-method/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "xxxxxxxx.com", referrer: "https://xxxxxxxx.com/my-account/add-payment-method/"
```

**Comment by ethanpil** [comment]
@mstein-ck I have not updated. I never received any confirmation that these issues are tested and addressed from your end and I am not willing to beta test on my live site.
